### ISSUE TITLE
Perpetuals / stop order error

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#4889] opened 2023-09-26 09:57 UTC
### Discussed in https://github.com/vegaprotocol/feedback/discussions/162

<div type='discussions-op-text'>

<sup>Originally posted by **nelseen** September 26, 2023</sup>
I'm not entirely sure if the perpetual feature has been set yet to function using the stop-order limit/market.
each time I attempt to use it I get an '' UNKNOWN ERROR OCCURRED"

<img width="1672" alt="Screenshot 2023-09-25 at 11 58 46 PM" src="https://github.com/vegaprotocol/feedback/assets/140764526/643e3bd9-a653-43b3-a553-76c54d37fc44">

1e246cd490f7c51aa048c87ebc75c30d00ef37cbcc2906ffcbd8c94810056dbb
</div>

**Comment by JonRay15** [comment] 2023-09-26 10:04
Lets make sure when we investigate this we update the user .... so let me know when someone picks this up.

**Comment by bglownia** [comment] 2023-09-29 13:46
This is caused by error in vega-snap.
Below version of vega-snap does not have this issue
https://github.com/vegaprotocol/vega-snap/tree/feature/stop-orders-and-referrals

**Comment by bglownia** [comment] 2023-09-29 15:08
Root cause
https://github.com/vegaprotocol/vega-snap/blob/main/packages/snap/src/ui.ts#L539/
If val equals null `typeof val === 'object'` is true /
It executes `prettyPrint(null)` which executes `Object,entries(null)` and throws "TypeError: Cannot convert undefined or null to object"

**Comment by bglownia** [comment] 2023-10-05 12:17
resolved by
https://github.com/vegaprotocol/vega-snap/pull/9

**Closed** 2023-10-05 12:16 UTC
Labels: Trading, 🐛 bug, feedback
