### ISSUE TITLE
Ensure users can disassociate without having to connect to the Vega wallet.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#594] opened 2022-06-20 18:30 UTC
It should be possible to take VEGA tokens that you have in your wallet (vesting or otherwise) away from a Vega key without having access to that Vega key.
This used to work but I think due to some logic simplification we lost the ability (perhaps because the associate and disassociate are treated as one form with two states).

The eth wallet side bar does already list the Vega keys that the connected eth wallet has associated too. this is useful but it would be better if the form just did this for you.

AC:
- [ ] on the disassociate form it lists all the addresses that VEGA has been associated to from the connected eth wallet
- [ ] user is able to select a association
- [ ] user is able to populate the amount input with the full amount of VEGA associated with the selected Vega key (string)
- [ ] use can toggle between doing this with vesting or standard VEGA
- [ ] on completion user is told what has happened and given a prompt to disassociate more (if there is more) or go back to staking.

**Comment by asiaznik** [comment] 2022-09-01 09:20
I believe it is a duplicate of #806 and #1137

**Closed** 2022-09-21 09:19 UTC
Labels: Token Frontend, 🐛 bug
