### ISSUE TITLE
Handle new account properly

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/frontend-monorepo#1391] opened 2022-09-20 09:03 UTC
## The Chore

Handle new account in libs/accounts/src/lib/accounts-data-provider.ts
When new account appears we are notified via subscription but there is missing data which we need

```
market {
    id
    tradableInstrument {
      instrument {
        name
      }
    }
  }
  asset {
    id
    symbol
    decimals
  }
```

We got two options here 
- change this provider be derived data provider and fetch assets, markets and accounts separately 
or
- re fetch accounts data when new account will appear

**Comment by mattrussell36** [comment] 2022-10-02 02:22
Closing as dupe of https://github.com/vegaprotocol/frontend-monorepo/issues/1491

**Closed by mattrussell36** 2022-10-02 02:22 UTC
Labels: Trading, chore
