### ISSUE TITLE
The links to community and discussion/feedback on vega explorer are not functioning

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#3796] opened 2023-05-17 09:29 UTC
## Description

Accessing the https://explorer.vega.xyz/ you can see the the links to community and share your feedback does not work.

## Steps to Reproduce

1. Go to https://explorer.vega.xyz/
2. Scroll down and click on vega.community and/or share feedback link on the bottom of the page
3. Does not take you to functioning pages

## Expected behavior

Feedback should take you to 
https://github.com/vegaprotocol/feedback/

Community should take you to 
https://community.vega.xyz/

## Screenshots

<img width="1457" alt="Screenshot 2023-05-17 at 10 17 48" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/53e8319e-65af-4f9a-8b8d-d7a5b28b58f5">

**Comment by edd** [comment] 2023-05-23 09:34
This is now fixed. Note that the 'Community' link was a red herring - it was intended to be a link to the node, which just happened to involve the word 'community' in the name. I've de-linkified this to avoid that ambiguity.

**Closed by edd** 2023-05-23 09:34 UTC
Labels: Block Explorer, 🐛 bug
