### ISSUE TITLE
Accounts table

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#153] opened 2022-03-28 01:57 UTC
- Fields
  - Asset symbol
  - Balance
  - Account type
  - Market name (if margin account)

Note: No collapsible rows for first pass

**Comment by gordsport** [comment] 2022-04-04 15:36
dupe of: https://github.com/vegaprotocol/frontend-monorepo/issues/185

**Closed by gordsport** 2022-04-04 15:36 UTC
Labels: Trading
