### ISSUE TITLE
Handle Enum type changes

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#982] opened 2022-08-09 11:08 UTC
From this PR:

https://github.com/vegaprotocol/vega/pull/5799/files#diff-be016f833f94c6069e96beb4873414c55bdfb7af1924c9c1b90eb709304ff90eL654

**Comment by gordsport** [comment] 2022-08-17 14:07
closing as duplicate of: 
- https://github.com/vegaprotocol/frontend-monorepo/issues/1031

**Closed by gordsport** 2022-08-17 14:07 UTC
Labels: blocked
