### ISSUE TITLE
Additional reward %age bug

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4415] opened 2023-07-27 11:26 UTC
Slack thread 

https://vegaprotocol.slack.com/archives/C02GZ0Q0NDC/p1690741050249269

Duplicate ticket 

https://github.com/vegaprotocol/frontend-monorepo/issues/4436

**Comment by edd** [comment] 2023-07-31 09:20
Dupe of #4436

**Closed** 2023-07-31 09:20 UTC
Labels: Governance
