### ISSUE TITLE
Node switcher popup not opening

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#858] opened 2022-07-25 14:52 UTC
The connected node popup doesn't reliably appear on https://console.fairground.wtf/ when the node is down. 

- Seen using chrome Version 103.0.5060.134 
- Easily replicated in an incognito window 
- Failed to fetch message remains on screen when visiting https://console.fairground.wtf/ rather than the expected behaviour of the "connected node" popup opening

Screenshots attached
<img width="991" alt="Screenshot 2022-07-25 at 15 35 12" src="https://user-images.githubusercontent.com/46783148/180806272-0ad0a5ff-8f78-4650-a500-1cdd5450b5fc.png">
<img width="1178" alt="Screenshot 2022-07-25 at 15 40 56" src="https://user-images.githubusercontent.com/46783148/180806289-8c74eb00-be9c-4f1e-ac05-ae18d85935ac.png">

**Comment by notbot00** [comment] 2022-08-01 16:08
redeployed fairground with the config url, and cannot reproduce this anymore. closing this for now.

**Closed by notbot00** 2022-08-01 16:08 UTC
Labels: Trading, Bug 🐞
