### ISSUE TITLE
Node switcher issues

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#856] opened 2022-07-25 13:32 UTC
I'm creating a ticket here with the list of issues/bugs that I've seen with the node switcher.

1.  Link to switch node should be disabled if there is no config url
2. After raising an error i.e. switching to incorrect node. The error stays in the modal after closing and opening it again
3. Input fake url and click check twice freezes the modal with the user unable to do anything else
4. Issue with nodes in `Mainnet` not connecting
5. Version/commit hash has un-clickable link which is underlined?
6. Should the switcher `check` the connection before `connecting`? I seem to be able to click connecting regardless

**Comment by notbot00** [comment] 2022-08-01 11:11
1. the consequence is that the user won't be able to enter a custom node url when we don't have a config list, it made sense in my head to still allow the switch to a custom node
2. cannot reproduce (for me the modal reloads all the data every time it closes / reopens)
3. has been fixed in: https://github.com/vegaprotocol/frontend-monorepo/pull/928
4. has been fixed in: https://github.com/vegaprotocol/frontend-monorepo/pull/892
5. cannot reproduce (it is unclickable only when running the code locally, works on fairground, for example)
6. i believe it does check the connection before allowing to connect, not sure how to reproduce this, will need more info on this part

**Closed** 2022-08-04 09:14 UTC
Labels: Block Explorer, Token Frontend, Bug 🐞
