### ISSUE TITLE
Wrong state saved in Connect Vega Wallet dialog

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#838] opened 2022-07-22 08:13 UTC
Wrong state is saved after closing Connect Vega Wallet by REST dialog. Please follow the reproduction steps or watch the attached video.

1. You’re on Vega Token app.
2. Click Connect Vega Wallet (in Vega wallet component) - Connectors list appears with one option - REST
3. Click REST - next dialog opens, REST details need to be provided
4. Close dialog.
5. Click Connect Vega Wallet again - REST dialog opens.

At the last step, dialog with connectors list should appear instead of REST details one. 

https://user-images.githubusercontent.com/24473278/180394854-6bb1fd3d-9434-4f5f-ab0f-57019b253eb8.mov

**Comment by dexturr** [comment] 2023-01-30 16:25
@radoslaw-szpiech this has been refactored twice so I am closing as not a bug, please reopen if that is not the case.

**Closed by dexturr** 2023-01-30 16:25 UTC
Labels: 🐛 bug, connect-vega-wallet, common
