### ISSUE TITLE
Portfolio: Add closed positions tab

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#841] opened 2022-07-22 13:51 UTC
### Proposed design
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1616%3A25672

![image](https://user-images.githubusercontent.com/1325606/180453498-dd6e1d30-22e0-4355-b5e8-802498c73e40.png)

**Comment by mattrussell36** [comment] 2022-10-02 04:51
Closing as dupe of #469

**Closed by mattrussell36** 2022-10-02 04:51 UTC
Labels: Trading
