### ISSUE TITLE
Configurable toast location

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2691] opened 2023-01-20 17:32 UTC
## Story

As a consumer of ui-toolkit
I want to be able to configure toast location
So that I can place it in the best location for the app I am building

## Acceptance Criteria 
- [ ] Toasts can be positioned, top (center), top-left, top-right, bottom (center), bottom-left, bottom-right

## Background

Configurable toast location, choose bottom of the screen or top type thing (right and left?)

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/215078750-6128dfa1-dd80-4e09-979c-db6db9b8659f.png)

**Comment by barnabee** [comment] 2023-01-20 17:46
Bottom centre is a good place for notifications too ;)

**Comment by jgadipriss** [comment] 2023-01-22 12:33
top right corner looks good

**Comment by mattrussell36** [comment] 2023-04-19 13:51
Closing as dupe of https://github.com/vegaprotocol/frontend-monorepo/issues/3232

**Closed by mattrussell36** 2023-04-19 13:51 UTC
Labels: Trading, refine
