### ISSUE TITLE
View market creation transaction placeholder

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2011] opened 2022-11-10 11:44 UTC
## Story

As a
I want
So that

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by edd** [comment] 2023-02-22 14:29
Dupe of #2111

**Closed by edd** 2023-02-22 14:29 UTC
Labels: Block Explorer
