### ISSUE TITLE
[console] Scrolling a lot in the order list makes it stop working

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#1240] opened 2022-09-02 22:36 UTC
https://user-images.githubusercontent.com/100769129/188242908-c3a6c839-bde7-444d-81dd-1a3a9939b832.mov

If you have a lot of orders in the orderbook and begin to scroll down it goes black after a while and then you cannot scroll up either so it is frozen, waited for minutes without difference.

Expected result:
To be able to scroll, having page or date filter,

Results:
All orders in one list which stops working.

**Comment by mattrussell36** [comment] 2022-11-16 07:40
@bglownia Wonder if we should look into using the date range for orders? Might be easier to handle compared to infinite scroll here?

**Comment by macqbat** [comment] 2022-11-22 13:34
can't reproduce the issue now. Seems to be possibly fixed by some other issue fixing(?)

**Comment by mattrussell36** [comment] 2022-11-22 20:29
This is now working again

**Closed by mattrussell36** 2022-11-22 20:29 UTC
Labels: Trading, 🐛 bug
