### ISSUE TITLE
Switching network on desktop wallet freezes wallet after have connected to governance

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#3757] opened 2023-05-14 15:38 UTC
## Description

Not sure how big of a problem this is but when you have chosen mainnet network and connects to 
https://governance.vega.xyz/, disconnect switch to Fairground and try to connect to (https://governance.fairground.wtf/) the wallet freezes at approve and needs to be restarted, then it works.

Actually after having connected to a governance page, e.g. mainnet, it seems that the wallet freezes when you try to change network.

## Steps to Reproduce

1. Go to https://governance.vega.xyz/ and connect desktop wallet with mainnet
2. disconnect, switch to fairground network
3. Go to https://governance.fairground.wtf and connect the wallet, OR just try to change network in wallet and see if it does not freeze
4. It freezes at approve, you can't click the button and you need to restart it

## Expected behavior

Should be able to connect and or switch network after you have connected to governance page.

**Desktop (please complete the following information):**

- OS: MacOS ARM
- Desktop Version 0.12.1

**Comment by pennyandrews** [comment] 2023-06-30 10:58
In wrong repo and duplicate of https://github.com/vegaprotocol/vegawallet-desktop/issues/694

**Closed by pennyandrews** 2023-06-30 10:58 UTC
Labels: 🐛 bug, desktop-wallet
