### ISSUE TITLE
Order amendment tech debt in Console

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5795] opened 2024-02-14 10:08 UTC
### Console issue 

Core have recently made a [change](https://github.com/vegaprotocol/vega/issues/9943) to support setting the new order size instead of defining a delta.

Looks like currently in Console we do this for the user and you set an amount and we work out the delta.

Now this new method exists we should remove that and just use the new method or it could be misleading.

## Additional details / background info

Old method with a delta

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/a8ca5a0c-b873-46d9-a308-690cb4a2ca60)

**Comment by edd** [comment] 2024-02-19 10:20
Dupe of #5774

**Closed by edd** 2024-02-19 10:20 UTC
Labels: Block Explorer, 🐛 bug
