### ISSUE TITLE
Remove/ hide all liquidation price from deal ticket estimations and positions table (for now, as it's incorrect)

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#2812] opened 2023-02-01 11:43 UTC
There is a core change planned (with research currently) that will give us a best and worst case margin number that we can use to work out the best and worse case liquidation price to give us an accurate range. We'd have to work out client side what the position would be.

Until this change has been implemented in core the decision has been to remove liquidation price. We will write another ticket to cover this work that can be planned when we have something workable from core. 

## Description

Liquidation price does not look correct on Console so we want to hide/remove it.

## Tasks

- [ ] Communicate with Dan in the community team to let him know the approach we are taking for this
- [ ] Implementat change to hide / remove
- [ ] Test
- [ ] Etc.

## Steps to Reproduce

1. Place a trade that fills
2. See the estimated liq price in the Positions view
4. See liquidation price that doesn't seem right: for example, short position with liq price below open price

## Expected behavior

See the correct a liquidation price

## Screenshots

![image](https://user-images.githubusercontent.com/62548908/216029417-5d7c59e4-f3bb-4332-9bf9-4e4894bec900.png)

## Additional context
Calculation: https://github.com/vegaprotocol/research/blob/master/notebooks/misc/Margin%20level%20price%20approximation.ipynb

Liquidation price estimation (behind the Place order button).

That is calculated like this:
(marginMaintenanceLevel - positionAccountBalance - generalAccountBalance) / volume + <markPrice-or-limitPrice>
If it’s <0 we display 0 or just ‘-’.
In positions table is calculated like this:

``` 
const liquidationPrice = BigNumber.maximum(
      0,
      marginMaintenance
        .minus(marginAccountBalance)
        .minus(generalAccountBalance)
        .dividedBy(openVolume)
        .plus(markPrice)
    );

```  
Few spotted differences by @MadalinaRaicu 

In positions table we are looking at the margin account balance (seems fair, at the moment when you create an order you may not have anything in your margin acc balance)

We use mark price for liq. price in positions table. that seems again alright. in orders we needed to account for limit price set by the user

**Comment by singwin** [comment] 2023-02-01 12:19
Hi，it's me. 
After I closed this position, everything was fine when I opened a new position again. 
By the way, the position in the picture should have been liquidated, but it will never be liquidated, because the liquidation price will follow the market price

**Comment by pennyandrews** [comment] 2023-02-02 16:12
Michael is going to see if he can reproduce this to shed more light into why it happened

**Comment by singwin** [comment] 2023-02-03 02:02
I am very clear that this is a real account reaction, not a front-end display error. 
I saw that the bug that caused this problem was fixed in the system today. So I can speak out now. Because the hedging (long2short or short2long) amount is not limited, the reverse trade can be super-high leveraged, resulting in miscalculation of the liquidated price, and that is it.

**Comment by bglownia** [comment] 2023-02-09 15:00
Formula to calculate liquidation price was taken from below notebook
https://github.com/vegaprotocol/research/blob/master/notebooks/misc/Misc%20position%20metrics.ipynb

**Comment by bglownia** [comment] 2023-02-09 16:52
I verified code carefully and there is no mistake in calculations. Both in positions table and deal ticket we are using same formula. 
When opening long position liquidation price is below mark price and when increasing position liquidation price also increase (to be closer to the mark price). 
When opening short position liquidation price is above mark price and when increasing position liquidation price decrease (to be closer to the mark price). 
So it looks like it works fine. If we would like to argue with the value it shows we should closely look at value of margin maintenance level which is provided by the API

**Closed** 2023-03-22 12:22 UTC
Labels: Trading, 🐛 bug, feedback, mainnet-sims
